package com.franciscogiraldo.fcog.grability.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP".
 */
public class App {

    private Long id;
    private String title;
    private String image;
    private String description;
    private String category;
    private String link;
    private Integer price;
    private Integer favorite;
    private Integer newSync;

    public App() {
    }

    public App(Long id) {
        this.id = id;
    }

    public App(Long id, String title, String image, String description, String category, String link, Integer price, Integer favorite, Integer newSync) {
        this.id = id;
        this.title = title;
        this.image = image;
        this.description = description;
        this.category = category;
        this.link = link;
        this.price = price;
        this.favorite = favorite;
        this.newSync = newSync;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Integer getFavorite() {
        return favorite;
    }

    public void setFavorite(Integer favorite) {
        this.favorite = favorite;
    }

    public Integer getNewSync() {
        return newSync;
    }

    public void setNewSync(Integer newSync) {
        this.newSync = newSync;
    }

}
