package com.franciscogiraldo.fcog.grability.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.franciscogiraldo.fcog.grability.db.App;

import com.franciscogiraldo.fcog.grability.db.AppDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appDaoConfig;

    private final AppDao appDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appDaoConfig = daoConfigMap.get(AppDao.class).clone();
        appDaoConfig.initIdentityScope(type);

        appDao = new AppDao(appDaoConfig, this);

        registerDao(App.class, appDao);
    }
    
    public void clear() {
        appDaoConfig.getIdentityScope().clear();
    }

    public AppDao getAppDao() {
        return appDao;
    }

}
